[2025-01-10T10:01:17.238+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-10T10:01:17.280+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_bash_decorator.get_file_stats manual__2025-01-10T10:01:12.886807+00:00 [queued]>
[2025-01-10T10:01:17.307+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_bash_decorator.get_file_stats manual__2025-01-10T10:01:12.886807+00:00 [queued]>
[2025-01-10T10:01:17.308+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-10T10:01:17.348+0000] {taskinstance.py:2889} INFO - Executing <Task(_BashDecoratedOperator): get_file_stats> on 2025-01-10 10:01:12.886807+00:00
[2025-01-10T10:01:17.408+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'example_bash_decorator', 'get_file_stats', 'manual__2025-01-10T10:01:12.886807+00:00', '--job-id', '9', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_bash_decorator.py', '--cfg-path', '/tmp/tmp_jjuuan4']
[2025-01-10T10:01:17.435+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask get_file_stats
[2025-01-10T10:01:17.438+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=7290) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-10T10:01:17.441+0000] {standard_task_runner.py:72} INFO - Started process 7303 to run task
[2025-01-10T10:01:17.739+0000] {task_command.py:467} INFO - Running <TaskInstance: example_bash_decorator.get_file_stats manual__2025-01-10T10:01:12.886807+00:00 [running]> on host f99ce696fe80
[2025-01-10T10:01:18.016+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_bash_decorator' AIRFLOW_CTX_TASK_ID='get_file_stats' AIRFLOW_CTX_EXECUTION_DATE='2025-01-10T10:01:12.886807+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-10T10:01:12.886807+00:00'
[2025-01-10T10:01:18.019+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-10T10:01:18.020+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-10T10:01:18.021+0000] {logging_mixin.py:190} INFO - Current task name:get_file_stats state:running start_date:2025-01-10 10:01:17.281717+00:00
[2025-01-10T10:01:18.022+0000] {logging_mixin.py:190} INFO - Dag name:example_bash_decorator and current dag run status:running
[2025-01-10T10:01:18.023+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-10T10:01:18.073+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-10T10:01:18.076+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'stat']
[2025-01-10T10:01:18.106+0000] {subprocess.py:99} INFO - Output:
[2025-01-10T10:01:18.114+0000] {subprocess.py:106} INFO - stat: missing operand
[2025-01-10T10:01:18.115+0000] {subprocess.py:106} INFO - Try 'stat --help' for more information.
[2025-01-10T10:01:18.116+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-01-10T10:01:18.142+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/bash.py", line 82, in execute
    return super().execute(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-10T10:01:18.153+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T10:01:18.154+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 10:01:17.281717+00:00 end:2025-01-10 10:01:18.151983+00:00 duration:0.870266
[2025-01-10T10:01:18.155+0000] {logging_mixin.py:190} INFO - Task:<Task(_BashDecoratedOperator): get_file_stats> dag:<DAG: example_bash_decorator> dagrun:<DagRun example_bash_decorator @ 2025-01-10 10:01:12.886807+00:00: manual__2025-01-10T10:01:12.886807+00:00, state:running, queued_at: 2025-01-10 10:01:12.906719+00:00. externally triggered: True>
[2025-01-10T10:01:18.156+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-01-10T10:01:18.157+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=example_bash_decorator, task_id=get_file_stats, run_id=manual__2025-01-10T10:01:12.886807+00:00, execution_date=20250110T100112, start_date=20250110T100117, end_date=20250110T100118
[2025-01-10T10:01:18.188+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-10T10:01:18.189+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task get_file_stats (Bash command failed. The command returned a non-zero exit code 1.; 7303)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/bash.py", line 82, in execute
    return super().execute(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-10T10:01:18.251+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-10T10:01:18.269+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
