[2025-01-13T07:38:48.047+0000] {processor.py:186} INFO - Started process (PID=12283) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:38:48.048+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:38:48.050+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:38:48.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:38:48.065+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:38:48.063+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 20
    )
SyntaxError: invalid syntax
[2025-01-13T07:38:48.067+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:38:48.092+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.051 seconds
[2025-01-13T07:39:18.387+0000] {processor.py:186} INFO - Started process (PID=12304) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:39:18.388+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:39:18.390+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:39:18.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:39:18.407+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:39:18.405+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 20
    )
SyntaxError: invalid syntax
[2025-01-13T07:39:18.408+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:39:18.432+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.051 seconds
[2025-01-13T07:39:41.607+0000] {processor.py:186} INFO - Started process (PID=12325) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:39:41.608+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:39:41.609+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:39:41.609+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:39:41.623+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:39:41.622+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 19
    schedule_interval='@daily')
SyntaxError: invalid syntax
[2025-01-13T07:39:41.624+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:39:41.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.042 seconds
[2025-01-13T07:39:42.639+0000] {processor.py:186} INFO - Started process (PID=12330) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:39:42.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:39:42.641+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:39:42.641+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:39:42.656+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:39:42.655+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 20
    
SyntaxError: invalid syntax
[2025-01-13T07:39:42.657+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:39:42.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.044 seconds
[2025-01-13T07:39:44.734+0000] {processor.py:186} INFO - Started process (PID=12335) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:39:44.735+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:39:44.737+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:39:44.736+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:39:44.752+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:39:44.750+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 21
    
SyntaxError: invalid syntax
[2025-01-13T07:39:44.752+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:39:44.776+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.048 seconds
[2025-01-13T07:40:00.811+0000] {processor.py:186} INFO - Started process (PID=12346) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:00.812+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:40:00.815+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:00.814+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:00.835+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:00.833+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 21
    def greet()
               ^
SyntaxError: expected ':'
[2025-01-13T07:40:00.836+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:00.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.060 seconds
[2025-01-13T07:40:01.902+0000] {processor.py:186} INFO - Started process (PID=12351) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:01.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:40:01.906+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:01.905+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:01.928+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:01.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 22
    
    ^
IndentationError: expected an indented block after function definition on line 21
[2025-01-13T07:40:01.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:01.957+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.072 seconds
[2025-01-13T07:40:18.182+0000] {processor.py:186} INFO - Started process (PID=12366) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:18.184+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:40:18.185+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:18.185+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:18.202+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:18.201+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 22
    
    ^
IndentationError: expected an indented block after function definition on line 21
[2025-01-13T07:40:18.203+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:18.228+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.053 seconds
[2025-01-13T07:40:21.219+0000] {processor.py:186} INFO - Started process (PID=12371) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:21.221+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:40:21.224+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:21.223+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:21.247+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:21.245+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 23
    
    ^
IndentationError: expected an indented block after function definition on line 21
[2025-01-13T07:40:21.248+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:21.274+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.064 seconds
[2025-01-13T07:40:22.270+0000] {processor.py:186} INFO - Started process (PID=12376) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:22.271+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:40:22.273+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:22.272+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:22.295+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:22.294+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 23
    @
     ^
SyntaxError: invalid syntax
[2025-01-13T07:40:22.296+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:22.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.058 seconds
[2025-01-13T07:40:27.411+0000] {processor.py:186} INFO - Started process (PID=12387) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:27.412+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:40:27.414+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:27.413+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:27.434+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:27.433+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 23
    @task()
           ^
IndentationError: unexpected unindent
[2025-01-13T07:40:27.435+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:27.457+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.054 seconds
[2025-01-13T07:40:34.510+0000] {processor.py:186} INFO - Started process (PID=12392) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:34.512+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:40:34.514+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:34.513+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:34.537+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:34.535+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 23
    @task(multiple_outputs=true)
                                ^
IndentationError: unexpected unindent
[2025-01-13T07:40:34.538+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:34.567+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.065 seconds
[2025-01-13T07:40:38.619+0000] {processor.py:186} INFO - Started process (PID=12397) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:38.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:40:38.621+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:38.621+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:38.633+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:38.632+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 23
    @task(multiple_outputs=True)
                                ^
IndentationError: unexpected unindent
[2025-01-13T07:40:38.634+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:38.656+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.043 seconds
[2025-01-13T07:40:40.691+0000] {processor.py:186} INFO - Started process (PID=12402) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:40.694+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:40:40.695+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:40.695+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:40.714+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:40.712+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 24
    
    ^
IndentationError: unexpected unindent
[2025-01-13T07:40:40.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:40.737+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.053 seconds
[2025-01-13T07:40:46.878+0000] {processor.py:186} INFO - Started process (PID=12417) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:46.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:40:46.883+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:46.882+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:46.912+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:46.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 24
    def get_name()
                  ^
SyntaxError: expected ':'
[2025-01-13T07:40:46.914+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:46.957+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.095 seconds
[2025-01-13T07:40:47.897+0000] {processor.py:186} INFO - Started process (PID=12422) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:47.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:40:47.900+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:47.900+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:47.917+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:47.915+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 25
    
    ^
IndentationError: expected an indented block after function definition on line 24
[2025-01-13T07:40:47.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:47.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.053 seconds
[2025-01-13T07:40:59.013+0000] {processor.py:186} INFO - Started process (PID=12433) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:59.015+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:40:59.016+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:59.016+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:59.040+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:40:59.035+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 16, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:40:59.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:40:59.066+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.059 seconds
[2025-01-13T07:41:09.148+0000] {processor.py:186} INFO - Started process (PID=12438) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:09.150+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:41:09.152+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:09.152+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:09.183+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:09.178+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 16, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:41:09.186+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:09.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.075 seconds
[2025-01-13T07:41:17.373+0000] {processor.py:186} INFO - Started process (PID=12453) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:17.375+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:41:17.377+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:17.376+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:17.403+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:17.400+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 27
    ''
     ^
SyntaxError: ':' expected after dictionary key
[2025-01-13T07:41:17.404+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:17.433+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.069 seconds
[2025-01-13T07:41:20.110+0000] {processor.py:186} INFO - Started process (PID=12458) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:20.111+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:41:20.113+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:20.112+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:20.140+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:20.138+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 27
    'last_name'
              ^
SyntaxError: ':' expected after dictionary key
[2025-01-13T07:41:20.142+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:20.165+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.066 seconds
[2025-01-13T07:41:24.258+0000] {processor.py:186} INFO - Started process (PID=12463) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:24.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:41:24.260+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:24.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:24.275+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:24.274+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 27
    'last_name':
               ^
SyntaxError: expression expected after dictionary key and ':'
[2025-01-13T07:41:24.276+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:24.295+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.043 seconds
[2025-01-13T07:41:25.290+0000] {processor.py:186} INFO - Started process (PID=12474) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:25.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:41:25.292+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:25.292+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:25.304+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:25.303+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 27
    'last_name': 
               ^
SyntaxError: expression expected after dictionary key and ':'
[2025-01-13T07:41:25.305+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:25.333+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.049 seconds
[2025-01-13T07:41:27.426+0000] {processor.py:186} INFO - Started process (PID=12479) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:27.428+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:41:27.430+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:27.429+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:27.463+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:27.457+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 16, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:41:27.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:27.492+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.076 seconds
[2025-01-13T07:41:45.707+0000] {processor.py:186} INFO - Started process (PID=12494) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:45.708+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:41:45.709+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:45.709+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:45.742+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:45.736+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 16, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:41:45.745+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:45.774+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.075 seconds
[2025-01-13T07:41:56.776+0000] {processor.py:186} INFO - Started process (PID=12505) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:56.777+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:41:56.779+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:56.778+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:56.823+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:56.815+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 16, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:41:56.828+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:56.857+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.088 seconds
[2025-01-13T07:41:58.879+0000] {processor.py:186} INFO - Started process (PID=12510) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:58.881+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:41:58.882+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:58.882+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:58.912+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:41:58.906+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 16, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:41:58.914+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:41:58.936+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.064 seconds
[2025-01-13T07:42:01.987+0000] {processor.py:186} INFO - Started process (PID=12515) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:01.988+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:42:01.990+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:01.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:02.035+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:02.026+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 16, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:42:02.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:02.071+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.096 seconds
[2025-01-13T07:42:05.059+0000] {processor.py:186} INFO - Started process (PID=12520) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:05.060+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:42:05.062+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:05.062+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:05.088+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:05.083+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 16, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:42:05.091+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:05.111+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.059 seconds
[2025-01-13T07:42:09.141+0000] {processor.py:186} INFO - Started process (PID=12525) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:09.143+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:42:09.145+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:09.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:09.167+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:09.165+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 34
    @task()
           ^
IndentationError: unexpected unindent
[2025-01-13T07:42:09.168+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:09.192+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.064 seconds
[2025-01-13T07:42:10.223+0000] {processor.py:186} INFO - Started process (PID=12530) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:10.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:42:10.226+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:10.226+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:10.248+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:10.246+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 35
    
    ^
IndentationError: unexpected unindent
[2025-01-13T07:42:10.248+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:10.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.054 seconds
[2025-01-13T07:42:13.534+0000] {processor.py:186} INFO - Started process (PID=12545) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:13.535+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:42:13.537+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:13.536+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:13.558+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:13.557+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 35
    def 
        ^
SyntaxError: invalid syntax
[2025-01-13T07:42:13.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:13.580+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.055 seconds
[2025-01-13T07:42:26.593+0000] {processor.py:186} INFO - Started process (PID=12556) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:26.595+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:42:26.597+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:26.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:26.623+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:26.618+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:42:26.626+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:26.648+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.063 seconds
[2025-01-13T07:42:36.779+0000] {processor.py:186} INFO - Started process (PID=12561) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:36.781+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:42:36.783+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:36.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:36.815+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:36.808+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:42:36.817+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:36.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.070 seconds
[2025-01-13T07:42:45.995+0000] {processor.py:186} INFO - Started process (PID=12576) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:45.996+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:42:45.997+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:45.997+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:46.022+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:46.017+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:42:46.024+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:46.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.057 seconds
[2025-01-13T07:42:49.133+0000] {processor.py:186} INFO - Started process (PID=12581) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:49.134+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:42:49.136+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:49.135+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:49.164+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:42:49.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:42:49.167+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:42:49.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.063 seconds
[2025-01-13T07:43:06.253+0000] {processor.py:186} INFO - Started process (PID=12592) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:06.254+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:43:06.255+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:06.254+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:06.277+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:06.272+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:43:06.280+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:06.307+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.061 seconds
[2025-01-13T07:43:11.380+0000] {processor.py:186} INFO - Started process (PID=12597) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:11.381+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:43:11.383+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:11.382+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:11.401+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:11.400+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 37
    name_dict = 
                ^
SyntaxError: invalid syntax
[2025-01-13T07:43:11.402+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:11.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.048 seconds
[2025-01-13T07:43:17.692+0000] {processor.py:186} INFO - Started process (PID=12612) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:17.693+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:43:17.695+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:17.694+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:17.717+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:17.713+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:43:17.719+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:17.742+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.057 seconds
[2025-01-13T07:43:20.653+0000] {processor.py:186} INFO - Started process (PID=12617) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:20.654+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:43:20.655+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:20.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:20.670+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:20.669+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 38
    age = 
          ^
SyntaxError: invalid syntax
[2025-01-13T07:43:20.671+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:20.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.045 seconds
[2025-01-13T07:43:24.801+0000] {processor.py:186} INFO - Started process (PID=12628) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:24.802+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:43:24.804+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:24.803+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:24.836+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:24.831+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:43:24.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:24.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.072 seconds
[2025-01-13T07:43:30.873+0000] {processor.py:186} INFO - Started process (PID=12633) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:30.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:43:30.876+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:30.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:30.901+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:30.896+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:43:30.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:30.927+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.060 seconds
[2025-01-13T07:43:34.934+0000] {processor.py:186} INFO - Started process (PID=12638) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:34.935+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:43:34.937+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:34.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:34.963+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:34.958+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:43:34.965+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:34.987+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.059 seconds
[2025-01-13T07:43:41.093+0000] {processor.py:186} INFO - Started process (PID=12643) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:41.094+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:43:41.095+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:41.095+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:41.122+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:41.117+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:43:41.125+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:41.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.064 seconds
[2025-01-13T07:43:43.146+0000] {processor.py:186} INFO - Started process (PID=12648) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:43.147+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:43:43.148+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:43.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:43.174+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:43.169+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:43:43.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:43.198+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.059 seconds
[2025-01-13T07:43:46.291+0000] {processor.py:186} INFO - Started process (PID=12663) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:46.292+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:43:46.293+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:46.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:46.310+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:46.306+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:43:46.311+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:46.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.045 seconds
[2025-01-13T07:43:49.419+0000] {processor.py:186} INFO - Started process (PID=12668) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:49.420+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:43:49.422+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:49.422+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:49.449+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:49.444+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:43:49.452+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:49.476+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.063 seconds
[2025-01-13T07:43:55.418+0000] {processor.py:186} INFO - Started process (PID=12679) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:55.419+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:43:55.421+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:55.420+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:55.447+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:55.442+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:43:55.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:55.468+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.056 seconds
[2025-01-13T07:43:57.529+0000] {processor.py:186} INFO - Started process (PID=12684) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:57.530+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:43:57.532+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:57.531+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:57.560+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:43:57.554+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:43:57.563+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:43:57.581+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.060 seconds
[2025-01-13T07:44:09.681+0000] {processor.py:186} INFO - Started process (PID=12689) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:44:09.682+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:44:09.684+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:44:09.683+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:44:09.710+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:44:09.705+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:44:09.712+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:44:09.733+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.059 seconds
[2025-01-13T07:44:11.760+0000] {processor.py:186} INFO - Started process (PID=12694) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:44:11.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:44:11.763+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:44:11.762+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:44:11.790+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:44:11.786+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:44:11.792+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:44:11.810+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.058 seconds
[2025-01-13T07:44:18.941+0000] {processor.py:186} INFO - Started process (PID=12709) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:44:18.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:44:18.944+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:44:18.943+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:44:18.961+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:44:18.959+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 43
    greet_dag = 
                ^
SyntaxError: invalid syntax
[2025-01-13T07:44:18.962+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:44:18.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.063 seconds
[2025-01-13T07:44:25.940+0000] {processor.py:186} INFO - Started process (PID=12720) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:44:25.941+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:44:25.942+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:44:25.942+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:44:25.961+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:44:25.959+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 45
    greet_dag = 
                ^
SyntaxError: invalid syntax
[2025-01-13T07:44:25.962+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:44:25.984+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.052 seconds
[2025-01-13T07:44:30.059+0000] {processor.py:186} INFO - Started process (PID=12725) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:44:30.061+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:44:30.063+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:44:30.062+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:44:30.104+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:44:30.096+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:44:30.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:44:30.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.085 seconds
[2025-01-13T07:45:00.396+0000] {processor.py:186} INFO - Started process (PID=12746) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:45:00.397+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:45:00.399+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:45:00.398+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:45:00.412+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:45:00.408+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 13, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:45:00.414+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:45:00.433+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.043 seconds
[2025-01-13T07:45:20.626+0000] {processor.py:186} INFO - Started process (PID=12761) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:45:20.627+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:45:20.629+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:45:20.628+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:45:20.655+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:45:20.649+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 12, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^
NameError: name 'dag' is not defined
[2025-01-13T07:45:20.657+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:45:20.680+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.061 seconds
[2025-01-13T07:45:30.737+0000] {processor.py:186} INFO - Started process (PID=12772) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:45:30.738+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:45:30.740+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:45:30.739+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:45:30.757+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:45:30.756+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 1
    from airflow.decorators  
                             ^
SyntaxError: invalid syntax
[2025-01-13T07:45:30.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:45:30.780+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.049 seconds
[2025-01-13T07:45:35.907+0000] {processor.py:186} INFO - Started process (PID=12777) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:45:35.908+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:45:35.909+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:45:35.909+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:45:35.940+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:45:35.935+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 12, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: dag() got an unexpected keyword argument 'startdate'
[2025-01-13T07:45:35.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:45:35.967+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.067 seconds
[2025-01-13T07:46:06.215+0000] {processor.py:186} INFO - Started process (PID=12798) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:46:06.216+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:46:06.218+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:46:06.217+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:46:06.233+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:46:06.229+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taskflow_api.py", line 12, in <module>
    @dag(dag_id='dag_taskflow_api',
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: dag() got an unexpected keyword argument 'startdate'
[2025-01-13T07:46:06.235+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:46:06.266+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.058 seconds
[2025-01-13T07:46:13.305+0000] {processor.py:186} INFO - Started process (PID=12803) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:46:13.307+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:46:13.308+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:46:13.308+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:46:13.345+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:46:13.638+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:46:13.636+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:dag_taskflow_api
[2025-01-13T07:46:13.655+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:46:13.655+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:dag_taskflow_api
[2025-01-13T07:46:13.665+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:46:13.665+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:dag_taskflow_api
[2025-01-13T07:46:13.677+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:46:13.677+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:dag_taskflow_api
[2025-01-13T07:46:13.686+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:46:13.686+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:dag_taskflow_api
[2025-01-13T07:46:13.696+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:46:13.695+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:dag_taskflow_api
[2025-01-13T07:46:13.705+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:46:13.704+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:dag_taskflow_api
[2025-01-13T07:46:13.706+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:46:13.706+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:46:13.724+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:46:13.724+0000] {dag.py:3262} INFO - Creating ORM DAG for dag_taskflow_api
[2025-01-13T07:46:13.740+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:46:13.740+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:46:13.764+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.467 seconds
[2025-01-13T07:46:39.023+0000] {processor.py:186} INFO - Started process (PID=12824) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:46:39.024+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:46:39.026+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:46:39.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:46:39.052+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:46:39.069+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:46:39.068+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:46:39.105+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:46:39.104+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:46:39.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.117 seconds
[2025-01-13T07:47:09.412+0000] {processor.py:186} INFO - Started process (PID=12845) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:47:09.414+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:47:09.416+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:47:09.416+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:47:09.449+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:47:09.487+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:47:09.486+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:47:09.527+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:47:09.527+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:47:09.558+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.154 seconds
[2025-01-13T07:47:39.861+0000] {processor.py:186} INFO - Started process (PID=12866) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:47:39.862+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:47:39.863+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:47:39.863+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:47:39.881+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:47:39.908+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:47:39.908+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:47:39.934+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:47:39.933+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:47:39.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.099 seconds
[2025-01-13T07:48:10.192+0000] {processor.py:186} INFO - Started process (PID=12896) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:48:10.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:48:10.196+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:48:10.195+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:48:10.222+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:48:10.256+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:48:10.256+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:48:10.286+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:48:10.285+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:48:10.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.124 seconds
[2025-01-13T07:48:40.565+0000] {processor.py:186} INFO - Started process (PID=12917) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:48:40.566+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:48:40.567+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:48:40.567+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:48:40.589+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:48:40.621+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:48:40.620+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:48:40.649+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:48:40.649+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:48:40.671+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.112 seconds
[2025-01-13T07:49:11.001+0000] {processor.py:186} INFO - Started process (PID=12938) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:49:11.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:49:11.004+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:49:11.004+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:49:11.025+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:49:11.062+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:49:11.062+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:49:11.098+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:49:11.098+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:49:11.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.130 seconds
[2025-01-13T07:49:41.395+0000] {processor.py:186} INFO - Started process (PID=12959) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:49:41.396+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:49:41.398+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:49:41.398+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:49:41.438+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:49:41.482+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:49:41.482+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:49:41.526+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:49:41.525+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:49:41.557+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.171 seconds
[2025-01-13T07:50:11.859+0000] {processor.py:186} INFO - Started process (PID=12981) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:50:11.861+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:50:11.864+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:50:11.863+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:50:11.896+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:50:11.930+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:50:11.930+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:50:11.958+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:50:11.957+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:50:11.983+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.133 seconds
[2025-01-13T07:50:42.242+0000] {processor.py:186} INFO - Started process (PID=13002) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:50:42.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:50:42.245+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:50:42.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:50:42.270+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:50:42.312+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:50:42.311+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:50:42.352+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:50:42.352+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:50:42.383+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.148 seconds
[2025-01-13T07:51:13.251+0000] {processor.py:186} INFO - Started process (PID=13023) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:51:13.252+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:51:13.254+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:51:13.254+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:51:13.280+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:51:13.316+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:51:13.316+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:51:13.350+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:51:13.350+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:51:13.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.130 seconds
[2025-01-13T07:51:44.045+0000] {processor.py:186} INFO - Started process (PID=13044) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:51:44.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:51:44.047+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:51:44.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:51:44.068+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:51:44.102+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:51:44.101+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:51:44.133+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:51:44.133+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:51:44.159+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.120 seconds
[2025-01-13T07:52:14.404+0000] {processor.py:186} INFO - Started process (PID=13065) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:52:14.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:52:14.407+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:52:14.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:52:14.426+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:52:14.454+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:52:14.454+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:52:14.481+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:52:14.481+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:52:14.506+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.108 seconds
[2025-01-13T07:52:44.765+0000] {processor.py:186} INFO - Started process (PID=13086) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:52:44.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:52:44.768+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:52:44.767+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:52:44.792+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:52:44.824+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:52:44.824+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:52:44.854+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:52:44.854+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:52:44.885+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.127 seconds
[2025-01-13T07:53:15.342+0000] {processor.py:186} INFO - Started process (PID=13107) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:53:15.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:53:15.345+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:53:15.345+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:53:15.378+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:53:15.409+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:53:15.409+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:53:15.449+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:53:15.448+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:53:15.477+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.141 seconds
[2025-01-13T07:53:45.725+0000] {processor.py:186} INFO - Started process (PID=13128) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:53:45.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:53:45.729+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:53:45.728+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:53:45.754+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:53:45.789+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:53:45.788+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:53:45.820+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:53:45.820+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:53:45.846+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.127 seconds
[2025-01-13T07:54:15.996+0000] {processor.py:186} INFO - Started process (PID=13149) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:54:15.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:54:15.999+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:54:15.999+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:54:16.022+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:54:16.057+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:54:16.056+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:54:16.090+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:54:16.090+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:54:16.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.130 seconds
[2025-01-13T07:54:46.379+0000] {processor.py:186} INFO - Started process (PID=13170) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:54:46.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:54:46.382+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:54:46.382+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:54:46.409+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:54:46.441+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:54:46.441+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:54:46.470+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:54:46.469+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:54:46.496+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.124 seconds
[2025-01-13T07:55:16.742+0000] {processor.py:186} INFO - Started process (PID=13191) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:55:16.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:55:16.745+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:55:16.744+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:55:16.768+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:55:16.806+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:55:16.805+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:55:16.838+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:55:16.838+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:55:16.863+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.129 seconds
[2025-01-13T07:55:47.100+0000] {processor.py:186} INFO - Started process (PID=13212) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:55:47.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:55:47.103+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:55:47.103+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:55:47.120+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:55:47.144+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:55:47.144+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:55:47.168+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:55:47.168+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:55:47.186+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.091 seconds
[2025-01-13T07:56:17.256+0000] {processor.py:186} INFO - Started process (PID=13233) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:56:17.257+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:56:17.259+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:56:17.259+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:56:17.281+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:56:17.313+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:56:17.313+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:56:17.341+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:56:17.341+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:56:17.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.114 seconds
[2025-01-13T07:56:47.603+0000] {processor.py:186} INFO - Started process (PID=13254) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:56:47.604+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:56:47.606+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:56:47.605+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:56:47.640+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:56:47.678+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:56:47.678+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:56:47.728+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:56:47.727+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:56:47.761+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.166 seconds
[2025-01-13T07:57:18.032+0000] {processor.py:186} INFO - Started process (PID=13275) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:57:18.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:57:18.035+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:57:18.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:57:18.054+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:57:18.082+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:57:18.081+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:57:18.112+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:57:18.112+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:57:18.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.106 seconds
[2025-01-13T07:57:48.372+0000] {processor.py:186} INFO - Started process (PID=13296) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:57:48.373+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:57:48.374+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:57:48.374+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:57:48.397+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:57:48.430+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:57:48.429+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:57:48.461+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:57:48.460+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:57:48.485+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.120 seconds
[2025-01-13T07:58:18.735+0000] {processor.py:186} INFO - Started process (PID=13317) to work on /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:58:18.736+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taskflow_api.py for tasks to queue
[2025-01-13T07:58:18.739+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:58:18.738+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:58:18.763+0000] {processor.py:925} INFO - DAG(s) 'dag_taskflow_api' retrieved from /opt/airflow/dags/dag_taskflow_api.py
[2025-01-13T07:58:18.797+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:58:18.797+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T07:58:18.830+0000] {logging_mixin.py:190} INFO - [2025-01-13T07:58:18.830+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_taskflow_api to 2025-01-13 00:00:00+00:00, run_after=2025-01-14 00:00:00+00:00
[2025-01-13T07:58:18.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taskflow_api.py took 0.126 seconds
